// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class PeopleData
{
	public class Row
	{
		public string name;
		public string greeting;
		public string timeFactor;
		public string combo;
		public string points;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.name = grid[i][0];
			row.greeting = grid[i][1];
			row.timeFactor = grid[i][2];
			row.combo = grid[i][3];
			row.points = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_greeting(string find)
	{
		return rowList.Find(x => x.greeting == find);
	}
	public List<Row> FindAll_greeting(string find)
	{
		return rowList.FindAll(x => x.greeting == find);
	}
	public Row Find_timeFactor(string find)
	{
		return rowList.Find(x => x.timeFactor == find);
	}
	public List<Row> FindAll_timeFactor(string find)
	{
		return rowList.FindAll(x => x.timeFactor == find);
	}
	public Row Find_combo(string find)
	{
		return rowList.Find(x => x.combo == find);
	}
	public List<Row> FindAll_combo(string find)
	{
		return rowList.FindAll(x => x.combo == find);
	}
	public Row Find_points(string find)
	{
		return rowList.Find(x => x.points == find);
	}
	public List<Row> FindAll_points(string find)
	{
		return rowList.FindAll(x => x.points == find);
	}

}